# Generated by Django 5.2.4 on 2025-08-25 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_last_pomodoro_duration_task_pomodoro_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_pomodoro_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='total_pomodoro_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
