# Generated by Django 5.2.6 on 2025-09-06 04:36

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_alter_task_last_pomodoro_duration_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE api_task DROP COLUMN IF EXISTS last_pomodoro_duration;",
            reverse_sql="-- No reverse"
        ),
        migrations.RunSQL(
            "ALTER TABLE api_task DROP COLUMN IF EXISTS total_pomodoro_time;",
            reverse_sql="-- No reverse"
        ),
        migrations.RunSQL(
            "ALTER TABLE api_task ADD COLUMN last_pomodoro_duration INTERVAL;",
            reverse_sql="ALTER TABLE api_task DROP COLUMN last_pomodoro_duration;"
        ),
        migrations.RunSQL(
            "ALTER TABLE api_task ADD COLUMN total_pomodoro_time INTERVAL DEFAULT INTERVAL '0';",
            reverse_sql="ALTER TABLE api_task DROP COLUMN total_pomodoro_time;"
        ),
    ]
